name: GitHub Action Test

on:
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  ANDROID_APP_PATH: "sample/application"

jobs:
  test-android-sdk:
    name: test
    runs-on: ubuntu-latest
    steps:
      #Get the code
      - uses: actions/checkout@v4

      # Check sdk
      - name: Check Android Sdk
        run: |
          chmod +x .github/scripts/install_android_sdk.sh
          ./.github/scripts/install_android_sdk.sh
